export OPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3

# Make zsh autocomplete with up arrow
# autoload -Uz history-search-end
# zle -N history-beginning-search-backward-end history-search-end
# zle -N history-beginning-search-forward-end history-search-end
# bindkey "$terminfo[kcuu1]" history-beginning-search-backward-end
# bindkey "$terminfo[kcud1]" history-beginning-search-forward-end

# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename '/Users/coreymeyer/.zshrc'
zstyle ':completion:*' menu select

autoload -Uz compinit
compinit

export GREP_OPTIONS='--color=always'
export GREP_COLOR='1;35;40'

export PATH=$PATH:/usr/local/go/bin

# PS1 Setup
source ~/.git_prompt

if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_NAME=${NAME// /-}
    VER=${VERSION_ID// /-}
    if [ -z ${VER} ]; then
        OS=$OS_NAME
    else
        OS="$OS_NAME-$VER"
    fi
else
    OS="$(uname -s)"
fi

SH=""
if [ "${ZSH_VERSION}" ]; then
    SH="zsh"
elif [ "${BASH_VERSION}" ]; then
    SH="bash"
fi

MACHINE="$(uname -m)"

docker_prompt=no

setopt PROMPT_SUBST

case "$(uname)" in
    "Darwin")
        if [ "$(docker ps) > /dev/null" ] || [ $docker_prompt=="no" ]; then
            # User Name
            PROMPT='%B%F{green}%n'
        else
            # User Name
            PROMPT='%B%F{green}DOCKER'
        fi
        # Machine Name
        PROMPT=$PROMPT'%F{white}-%F{magenta}%m'
        # CPU Type
        PROMPT=$PROMPT'%F{white}-%F{cyan}$CPUTYPE'
        # OS
        PROMPT=$PROMPT'%F{white}:%F{red}$(sw_vers -productName)-$(sw_vers -productVersion)%f'
        # Shell
        PROMPT=$PROMPT'%F{white}%F{white}-%f%F{magenta}$SH%f'
        # Directory
        PROMPT=$PROMPT':%f%F{blue}%~%f\$%b%f%F{white}%f '
        ;;
    "Linux")
        if [ "$(docker ps) > /dev/null" ] || [ $docker_prompt=="no" ]; then
            # User Name
            PROMPT='%B%F{green}%n'
        else
            # User Name
            PROMPT='%B%F{green}DOCKER'
        fi
        # Machine Name
        PROMPT=$PROMPT'%F{white}-%F{magenta}%m'
        # CPU Type
        PROMPT=$PROMPT'%F{white}-%F{cyan}$CPUTYPE'
        # OS
        PROMPT=$PROMPT'%F{white}:%F{red}$OS'
        # Shell
        PROMPT=$PROMPT'%F{white}-%f%F{magenta}$SH%f'
        # Directory
        PROMPT=$PROMPT'%F{white}:%f%F{blue}%~%f\$%b '
        ;;
esac
RPROMPT='$(git_prompt)%F{white}'
# PS1 setup

# enable color support of ls and also add handy aliases

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
set -o monitor

# some more ls aliases
# color designators are as follows:
# 
# a     black
# b     red
# c     green
# d     brown
# e     blue
# f     magenta
# g     cyan
# h     light grey
# A     bold black, usually shows up as dark grey
# B     bold red
# C     bold green
# D     bold brown, usually shows up as yellow
# E     bold blue
# F     bold magenta
# G     bold cyan
# H     bold light grey; looks like bright white
# x     default foreground or background
# 
# The order of the attributes are as follows:
# 
# 1.   directory
# 2.   symbolic link
# 3.   socket
# 4.   pipe
# 5.   executable
# 6.   block special
# 7.   character special
# 8.   executable with setuid bit set
# 9.   executable with setgid bit set
# 10.  directory writable to others, with sticky bit
# 11.  directory writable to others, without sticky bit
# 12.  dataless file
#
export LSCOLORS="ExGxCxdxCxegedabagacadah"

alias ls='ls -G'
alias ll='ls -lFh'
alias la='ls -Al'
alias l='ls -CF'

export PATH=~/.local/bin:$PATH

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi
if [ -f ~/.zsh_aliases ]; then
    . ~/.zsh_aliases
fi
